apiVersion: v1
kind: Template
metadata:
  name: solace-xml-soap-datagenerator
  annotations:
    description: Sample Spring Boot Application that demonstrate messaging with the Solace VMR - generators XML/SOAP Bank Transactions
    iconClass: icon-phalcon
    tags: 'instant-app,springboot,maven,java'
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-data-generator-soap'
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git:
          uri: '${GIT_URI}'
          ref: '${GIT_REF}'
        contextDir: ''
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
#            name: 's2i-java:latest'
            name: 'jdk-us-app:latest'
      output:
        to:
          kind: ImageStreamTag
          name: '${APPLICATION_NAME}-data-generator-soap:latest'
      resources: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-data-generator-soap'
    spec:
      dockerImageRepository: ''
      tags:
        - name: latest
#  - kind: ImageStream
#    apiVersion: v1
#    metadata:
#      name: '${APPLICATION_NAME}-data-generator-soap'
#    spec:
#      dockerImageRepository: ''
#      tags:
#        - name: latest
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-data-generator-soap'
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - '${APPLICATION_NAME}-data-generator-soap'
            from:
              kind: ImageStreamTag
              name: '${APPLICATION_NAME}-data-generator-soap:latest'
      replicas: 1
      selector:
        deploymentconfig: '${APPLICATION_NAME}-data-generator-soap'
      template:
        metadata:
          labels:
            deploymentconfig: '${APPLICATION_NAME}-data-generator-soap'
        spec:
          containers:
            - name: '${APPLICATION_NAME}-data-generator-soap'
              image: '${APPLICATION_NAME}-data-generator-soap'
              ports:
                - containerPort: 20010
                  protocol: TCP
              env:
              - name: 'SOL_HOST'
                value: '${SOL_HOST}'
              - name: 'SOL_USER'
                value: '${SOL_USER}'
              - name: 'SOL_PASSWORD'
                value: '${SOL_PASSWORD}'
              - name: 'SOL_RATE'
                value: '${SOL_RATE}'
              - name: 'SOL_URL'
                value: '${SOL_URL}' 
              - name: 'SOL_PORT'
                value: ${SOL_PORT}
#              livenessProbe:
#                tcpSocket:
#                  port: 55555
#                initialDelaySeconds: 30
#                timeoutSeconds: 1
              resources: {}
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          dnsPolicy: ClusterFirst
          
parameters:
  - name: APPLICATION_NAME
    displayName: Application name
    description: The name for this Data Generator application.
    value: bank-simulator-soap-xml
    required: true
  - name: SOL_HOST
    description: The address for the Solace Messages Router -- do not append port to address
    value: test-cluster-svc.vmr-openshift-demo.svc
    required: true
  - name: SOL_USER
    description: The client name for access to the Solace Message Broker
    value: 'heinz1'
    required: true
  - name: SOL_PASSWORD
    description: The password for the Solace client
    value: 'heinz1'
    required: true
  - name: SOL_RATE
    description: The rate the generator is supposed to send messages is messages/second
    value: '1'
    required: false
  - name: SOL_URL
    description: 'The topic to send messages, it can be the Queue Network Name, it must start with /TOPIC or /QUEUE'
    value: '/TOPIC/bank/data/xml'
    required: false
  - name: SOL_PORT
    decription: The port that that the Solace Broker is listening for REST communications
    value: '20010'
    required: true
  - name: GIT_URI
    description: Git source URI for application
    value: 'https://github.com/hschaffner/solace_openshift_xml_soap_datagenerator'
  - name: GIT_REF
    description: Git branch/tag reference
    value: 'master'

 
labels:
  application: solace-xml-soap-datagenerator
  createdBy: template-solace-xml-soap-datagenerator
          
